# Quarkus Configuration
site.content-dir=content
site.url=https://brew.omatheusmesmo.dev
site.future=false
site.draft=false
site.collections.brews.from-data.id-key=_key
site.collections.brews.layout=brew-post
site.collections.brews.future=false
%dev.site.future=true

# Server configuration
quarkus.http.port=8080

# Qute configuration
# Qute configuration
