name: Roq Site Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"
      - "AUTHORING.md"
      - "LICENSE"
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Generate Roq Site
        uses: quarkiverse/quarkus-roq@v1.1
        with:
          java-version: "25"
          maven-executable: mvn
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
